<a href="https://colab.research.google.com/github/yin-penghang/AMAT593/blob/main/18_Applications_III/01_Collaborative_Filtering_Recommendation_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Collaborative Filtering Recommendation Systems

[Collaborative filtering](https://en.wikipedia.org/wiki/Collaborative_filtering) aims to fill in the missing entries of a user-item rating matrix with predicted ratings, so that users are recomended new items based on the predicted ratings.

In this notebook, we will introduce the classical matrix factorization model for collaborative filtering as well as the state-of-the-arts based on neural networks.


<img src="https://github.com/yin-penghang/AMAT593/blob/main/figs/15_CF.png?raw=true" width = '400'>

# Matrix Factorization

Collaborative filtering is an application of matrix factorization to identify the relationship between items’ and users’ entities. With the input of users’ ratings on some of the items, we would like to predict how the users would rate the other items so the users can get the recommendation based on the prediction.

Suppose we have the user-item rating matrix $\mathbf{R}\in\mathbb{R}^{m\times n}$ for $m$ users and $n$ items, and the ratings are integers ranging from 1 to 5:

<img src= 'https://github.com/yin-penghang/AMAT593/blob/main/figs/15_rating_matrix.png?raw=true' width = '800'>

The $(i,j)$-th entry $r_{i,j}$ represents the $i$-th user's rating on the $j$-th item.
The rating matrix $\mathbf{R}\in\mathbb{R}^{m\times n}$ has a large portion of entries/ratings missing, and our goal here is to impute the full matrix.

Matrix factorization model assumes: every item has the same set of $k$ **latent factors** based on which a user will give the rating, where **$k$ is much less than the number of users and the number of items**. Maybe one factor means "movies with frantic chases", another factor might mean "movies with a plot twist", etc.

Let $\mathbf{q}_j \in\mathbb{R}^k$ be the $j$-th item's **components** in the $k$ latent factors and $\mathbf{p}_i\in\mathbb{R}^k$ be the $i$-th user's **personal preferences** on these $k$ latent factors, e.g.,

    Movie j = 0.5 x frantic chases + 0.2 x plot twist + ...
    
    User i = 0.3 x fan of frantic chases + 1.8 x fan of plot twist + ...

In practice, the latent factors are opaque. Given $\mathbf{q}_j$ and $\mathbf{p}_i$, the model generates the rating:

$$
\hat{r}_{i,j} = \mathbf{p}_i^\top \mathbf{q}_j
$$

In matrix form, denote by $\mathbf{P} = \begin{bmatrix} | \qquad | \\ \mathbf{p}_1 \cdots \mathbf{p}_m \\ | \qquad | \end{bmatrix}\in\mathbb{R}^{k\times m}$ the user latent matrix, and $\mathbf{Q} = \begin{bmatrix} | \qquad | \\ \mathbf{q}_1 \cdots \mathbf{q}_n \\ | \qquad | \end{bmatrix}\in\mathbb{R}^{k\times n}$ the item latent matrix, then the predicted rating matrix has the **low-rank matrix factorization**

$$
\hat{\mathbf{R}} = \mathbf{P}^\top \, \mathbf{Q}\in\mathbb{R}^{m\times n}
$$

<img src='https://github.com/yin-penghang/AMAT593/blob/main/figs/15_MatFacto.png?raw=true' width = '500'>

For any observed rating $r_{i,j}\in\mathbf{R}$, $\hat{\mathbf{R}}$ satisfies

$$
\hat{r}_{i,j} = \mathbf{p}_i^\top \mathbf{q}_j \approx r_{i,j}.
$$

**Under the constraints above, we aim to infer the user latent matrix $\mathbf{P}$ and item latent matrix $\mathbf{Q}$** by solving

$$
\min_{\{\mathbf{p}_i\}_{i=1}^m, \{\mathbf{q}_j\}_{j=1}^n} \; \sum_{\mbox{ observed } r_{i,j}} (r_{i,j} - \mathbf{p}_i^\top \mathbf{q}_j)^2
+ \lambda(\|\mathbf{p}_i\|^2 + \|\mathbf{q}_j\|^2)
$$

### The Algorithm

The minimization is performed by a straightforward mini-batch gradient descent: for an observed rating $r_{i,j}$, iterate

\begin{align}
\mathbf{p}_i \leftarrow \mathbf{p}_i - \eta  \left( (\mathbf{p}_i^\top \mathbf{q}_j - r_{i,j})\mathbf{q}_j + \lambda \mathbf{p}_i \right) \\
\mathbf{q}_j \leftarrow \mathbf{q}_j - \eta  \left( (\mathbf{p}_i^\top \mathbf{q}_j - r_{i,j})\mathbf{p}_i + \lambda \mathbf{q}_j \right)
\end{align}

The above iterations are known as the SVD algorithm, as popularized by [Simon Funk](https://sifter.org/~simon/journal/20061211.html) during the Netflix Prize, although
**it is actually NOT [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) which computes the factorization of a full matrix.** The more appropriate term for what Funk did is **matrix factorization**.

## Tensorflow Implementation

We implement matrix factorization model using the Tensorflow/Keras libraries. The key for the implementation is to represent the user latent matrix $P\in\mathbb{R}^{k\times m}$ and item latent matrix $Q\in\mathbb{R}^{k\times n}$ with two **Embedding** layers. With this notion, $P$ and $Q$ can be viewed as trainable weight matrices of the model.

In [ ]:
import pandas as pd
import numpy as np
# import random

In [ ]:
import tensorflow as tf
from keras.models import Model, Sequential
from keras import regularizers
from keras.layers import Embedding, Flatten, Input, dot
from tensorflow.keras.utils import model_to_dot
from IPython.display import SVG, HTML

In [ ]:
def MatrixFacto(n_users, n_movies, latent_dim):

    movie_input = Input(shape=[1])
    movie_embedding = Embedding(input_dim = n_movies, output_dim = latent_dim, embeddings_regularizer=regularizers.L2(l2=1e-6))(movie_input)
    movie_vec = Flatten()(movie_embedding)

    user_input = Input(shape=[1])
    user_embedding = Embedding(input_dim = n_users, output_dim = latent_dim, embeddings_regularizer=regularizers.L2(l2=1e-6))(user_input)
    user_vec = Flatten()(user_embedding)

    dot_prod = dot([movie_vec, user_vec], axes=1)


    model = Model(inputs = [user_input, movie_input], outputs = dot_prod)
    model.compile(loss = 'mse', optimizer = 'adam', metrics = [tf.keras.metrics.RootMeanSquaredError(name='rmse')])


    return model

### MovieLens Dataset

MovieLens small dataset contains ~100,000 ratings from ~600 users on ~9700 movies.

In [ ]:
from google.colab import files

# Reading ratings file
print("Please upload the 'ratings.csv' file from your local machine.")
uploaded = files.upload()

# Assuming the uploaded file is named 'ratings.csv'.
# If you uploaded a file with a different name, please adjust 'file_name' below.
file_name = list(uploaded.keys())[0] if uploaded else 'ratings.csv'

data = pd.read_csv(file_name, sep=',', encoding='latin-1', usecols=['userId','movieId','rating'])
data.head(10)

Please upload the 'ratings.csv' file from your local machine.

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0
5       1       70     3.0
6       1      101     5.0
7       1      110     4.0
8       1      151     5.0
9       1      157     5.0

In [ ]:
print(data.movieId.unique())

[     1      3      6 ... 160836 163937 163981]

In [ ]:
print(data.userId.unique())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610]

Need to map movie IDs to `[0, n_movies-1]` and user IDs to `[0, n_user -1]`. Note that the movie IDs are not consecutive.

In [ ]:
movie_id_to_new_id = dict()
id = 0
for index, row in data.iterrows():
    if movie_id_to_new_id.get(row['movieId']) is None:
        movie_id_to_new_id[row['movieId']] = id
        data.at[index, 'movieId'] = id
        id += 1
    else:
        data.at[index, 'movieId'] = movie_id_to_new_id.get(row['movieId'])

In [ ]:
data.userId = data.userId-1

In [ ]:
data.head(10)

   userId  movieId  rating
0       0        0     4.0
1       0        1     4.0
2       0        2     4.0
3       0        3     5.0
4       0        4     5.0
5       0        5     3.0
6       0        6     5.0
7       0        7     4.0
8       0        8     5.0
9       0        9     5.0

In [ ]:
n_users = data.userId.unique().shape[0]
n_movies = data.movieId.unique().shape[0]
print('Number of users = ' + str(n_users) + '\nNumber of movies = ' + str(n_movies))

Number of users = 610
Number of movies = 9724

Let's first check the sparsity of the ratings dataset, i.e., the percentage of missing ratings:

In [ ]:
sparsity = round(1.0 - len(data) / float(n_users * n_movies), 3)
print('The sparsity level of MovieLens dataset is ' +  str(sparsity * 100) + '%')

The sparsity level of MovieLens dataset is 98.3%

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train, test = train_test_split(data, test_size=0.2, random_state = 101)
X_tr, y_tr = [train.userId, train.movieId], train.rating
X_te, y_te = [test.userId, test.movieId], test.rating

Instantiate a ``MatrixFacto``  algorithm object with specified hyperparameters:

In [ ]:
latent_dim = 10
MF_model = MatrixFacto(n_users, n_movies, latent_dim)
MF_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_3       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_2         │ (None, 1, 10)     │     97,240 │ input_layer_2[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_3         │ (None, 1, 10)     │      6,100 │ input_layer_3[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_2 (Flatten) │ (None, 10)        │          0 │ embedding_2[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_3 (Flatten) │ (None, 10)        │          0 │ embedding_3[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_1 (Dot)         │ (None, 1)         │          0 │ flatten_2[0][0],  │
│                     │                   │            │ flatten_3[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 103,340 (403.67 KB)

 Trainable params: 103,340 (403.67 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from keras.callbacks import EarlyStopping, ModelCheckpoint

In [ ]:
path_checkpt = "MF_checkpt.weights.h5"
es_callback = EarlyStopping(monitor="val_rmse", patience=5)

modelckpt_callback = ModelCheckpoint(
    monitor="val_rmse",
    filepath=path_checkpt,
    verbose=1,
    save_weights_only=True,
    save_best_only=True,
)

In [ ]:
history = MF_model.fit(X_tr, y_tr, validation_data=(X_te, y_te), batch_size =128, epochs=40, callbacks=[es_callback, modelckpt_callback])

Epoch 1/40
631/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3076 - rmse: 3.6479
Epoch 1: val_rmse improved from None to 3.38340, saving model to MF_checkpt.weights.h5

Epoch 1: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 13.0086 - rmse: 3.6067 - val_loss: 11.4480 - val_rmse: 3.3834
Epoch 2/40
617/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3983 - rmse: 3.0604
Epoch 2: val_rmse improved from 3.38340 to 2.17545, saving model to MF_checkpt.weights.h5

Epoch 2: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 7.5692 - rmse: 2.7509 - val_loss: 4.7360 - val_rmse: 2.1754
Epoch 3/40
628/631 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.8636 - rmse: 1.9631
Epoch 3: val_rmse improved from 2.17545 to 1.70207, saving model to MF_checkpt.weights.h5

Epoch 3: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 3.4065 - rmse: 1.8444 - val_loss: 2.9027 - val_rmse: 1.7021
Epoch 4/40
628/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3557 - rmse: 1.5326
Epoch 4: val_rmse improved from 1.70207 to 1.48307, saving model to MF_checkpt.weights.h5

Epoch 4: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.2141 - rmse: 1.4858 - val_loss: 2.2067 - val_rmse: 1.4831
Epoch 5/40
610/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7321 - rmse: 1.3132
Epoch 5: val_rmse improved from 1.48307 to 1.35457, saving model to MF_checkpt.weights.h5

Epoch 5: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.6648 - rmse: 1.2872 - val_loss: 1.8433 - val_rmse: 1.3546
Epoch 6/40
624/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4060 - rmse: 1.1820
Epoch 6: val_rmse improved from 1.35457 to 1.27271, saving model to MF_checkpt.weights.h5

Epoch 6: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.3531 - rmse: 1.1593 - val_loss: 1.6294 - val_rmse: 1.2727
Epoch 7/40
618/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1680 - rmse: 1.0762
Epoch 7: val_rmse improved from 1.27271 to 1.21821, saving model to MF_checkpt.weights.h5

Epoch 7: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.1569 - rmse: 1.0709 - val_loss: 1.4945 - val_rmse: 1.2182
Epoch 8/40
622/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0278 - rmse: 1.0085
Epoch 8: val_rmse improved from 1.21821 to 1.18103, saving model to MF_checkpt.weights.h5

Epoch 8: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.0246 - rmse: 1.0068 - val_loss: 1.4062 - val_rmse: 1.1810
Epoch 9/40
614/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9250 - rmse: 0.9557
Epoch 9: val_rmse improved from 1.18103 to 1.15419, saving model to MF_checkpt.weights.h5

Epoch 9: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.9324 - rmse: 0.9595 - val_loss: 1.3443 - val_rmse: 1.1542
Epoch 10/40
630/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8554 - rmse: 0.9182
Epoch 10: val_rmse improved from 1.15419 to 1.13486, saving model to MF_checkpt.weights.h5

Epoch 10: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.8654 - rmse: 0.9235 - val_loss: 1.3007 - val_rmse: 1.1349
Epoch 11/40
613/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7977 - rmse: 0.8858
Epoch 11: val_rmse improved from 1.13486 to 1.12169, saving model to MF_checkpt.weights.h5

Epoch 11: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.8161 - rmse: 0.8961 - val_loss: 1.2715 - val_rmse: 1.1217
Epoch 12/40
627/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7673 - rmse: 0.8682
Epoch 12: val_rmse improved from 1.12169 to 1.11261, saving model to MF_checkpt.weights.h5

Epoch 12: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7783 - rmse: 0.8745 - val_loss: 1.2518 - val_rmse: 1.1126
Epoch 13/40
612/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7355 - rmse: 0.8494
Epoch 13: val_rmse improved from 1.11261 to 1.10604, saving model to MF_checkpt.weights.h5

Epoch 13: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7499 - rmse: 0.8578 - val_loss: 1.2377 - val_rmse: 1.1060
Epoch 14/40
612/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7171 - rmse: 0.8382
Epoch 14: val_rmse improved from 1.10604 to 1.10138, saving model to MF_checkpt.weights.h5

Epoch 14: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7275 - rmse: 0.8443 - val_loss: 1.2278 - val_rmse: 1.1014
Epoch 15/40
617/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6952 - rmse: 0.8248
Epoch 15: val_rmse improved from 1.10138 to 1.09674, saving model to MF_checkpt.weights.h5

Epoch 15: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7098 - rmse: 0.8336 - val_loss: 1.2180 - val_rmse: 1.0967
Epoch 16/40
618/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6838 - rmse: 0.8176
Epoch 16: val_rmse improved from 1.09674 to 1.09486, saving model to MF_checkpt.weights.h5

Epoch 16: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.6956 - rmse: 0.8248 - val_loss: 1.2142 - val_rmse: 1.0949
Epoch 17/40
631/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6748 - rmse: 0.8119
Epoch 17: val_rmse improved from 1.09486 to 1.09300, saving model to MF_checkpt.weights.h5

Epoch 17: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 0.6833 - rmse: 0.8171 - val_loss: 1.2104 - val_rmse: 1.0930
Epoch 18/40
631/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6581 - rmse: 0.8013
Epoch 18: val_rmse improved from 1.09300 to 1.09232, saving model to MF_checkpt.weights.h5

Epoch 18: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6739 - rmse: 0.8111 - val_loss: 1.2092 - val_rmse: 1.0923
Epoch 19/40
613/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6555 - rmse: 0.7996
Epoch 19: val_rmse improved from 1.09232 to 1.09170, saving model to MF_checkpt.weights.h5

Epoch 19: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6648 - rmse: 0.8053 - val_loss: 1.2081 - val_rmse: 1.0917
Epoch 20/40
623/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6415 - rmse: 0.7906
Epoch 20: val_rmse did not improve from 1.09170
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6573 - rmse: 0.8006 - val_loss: 1.2093 - val_rmse: 1.0921
Epoch 21/40
621/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6393 - rmse: 0.7891
Epoch 21: val_rmse improved from 1.09170 to 1.09155, saving model to MF_checkpt.weights.h5

Epoch 21: finished saving model to MF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.6503 - rmse: 0.7960 - val_loss: 1.2082 - val_rmse: 1.0916
Epoch 22/40
611/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6302 - rmse: 0.7832
Epoch 22: val_rmse did not improve from 1.09155
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6432 - rmse: 0.7915 - val_loss: 1.2091 - val_rmse: 1.0919
Epoch 23/40
617/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6228 - rmse: 0.7783
Epoch 23: val_rmse did not improve from 1.09155
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6365 - rmse: 0.7871 - val_loss: 1.2114 - val_rmse: 1.0929
Epoch 24/40
615/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6218 - rmse: 0.7776
Epoch 24: val_rmse did not improve from 1.09155
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6298 - rmse: 0.7828 - val_loss: 1.2113 - val_rmse: 1.0928
Epoch 25/40
627/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6093 - rmse: 0.7695
Epoch 25: val_rmse did not improve from 1.09155
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6223 - rmse: 0.7779 - val_loss: 1.2142 - val_rmse: 1.0940
Epoch 26/40
608/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5997 - rmse: 0.7632
Epoch 26: val_rmse did not improve from 1.09155
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6144 - rmse: 0.7727 - val_loss: 1.2127 - val_rmse: 1.0933

### Model evaluation

Load the best validated model and check the validation error

In [ ]:
MF_model.load_weights(path_checkpt)
MF_model.evaluate(X_te, y_te)

631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 1.2082 - rmse: 1.0916

[1.208220362663269, 1.0915533304214478]

### Prediction

In [ ]:
df = test[test['userId'] == 0]
df

     userId  movieId  rating
204       0      204     4.0
215       0      215     5.0
83        0       83     3.0
71        0       71     5.0
131       0      131     4.0
178       0      178     5.0
16        0       16     3.0
225       0      225     5.0
170       0      170     2.0
5         0        5     3.0
203       0      203     5.0
18        0       18     5.0
230       0      230     4.0
222       0      222     5.0
66        0       66     4.0
48        0       48     5.0
0         0        0     4.0
72        0       72     4.0
2         0        2     4.0
93        0       93     3.0
42        0       42     3.0
207       0      207     3.0
115       0      115     5.0
82        0       82     5.0
113       0      113     4.0
105       0      105     5.0
221       0      221     4.0
149       0      149     5.0
184       0      184     5.0
31        0       31     5.0
175       0      175     4.0
1         0        1     4.0
111       0      111     5.0
107       0      107     3.0
46        0       46     5.0
39        0       39     3.0
56        0       56     5.0
139       0      139     4.0
88        0       88     5.0
98        0       98     5.0
55        0       55     5.0
14        0       14     4.0
87        0       87     5.0
218       0      218     4.0
216       0      216     4.0
129       0      129     3.0
117       0      117     4.0

In [ ]:
df = df.sort_values(by = 'movieId')
df = df.reset_index(drop=True)
df

    userId  movieId  rating
0        0        0     4.0
1        0        1     4.0
2        0        2     4.0
3        0        5     3.0
4        0       14     4.0
5        0       16     3.0
6        0       18     5.0
7        0       31     5.0
8        0       39     3.0
9        0       42     3.0
10       0       46     5.0
11       0       48     5.0
12       0       55     5.0
13       0       56     5.0
14       0       66     4.0
15       0       71     5.0
16       0       72     4.0
17       0       82     5.0
18       0       83     3.0
19       0       87     5.0
20       0       88     5.0
21       0       93     3.0
22       0       98     5.0
23       0      105     5.0
24       0      107     3.0
25       0      111     5.0
26       0      113     4.0
27       0      115     5.0
28       0      117     4.0
29       0      129     3.0
30       0      131     4.0
31       0      139     4.0
32       0      149     5.0
33       0      170     2.0
34       0      175     4.0
35       0      178     5.0
36       0      184     5.0
37       0      203     5.0
38       0      204     4.0
39       0      207     3.0
40       0      215     5.0
41       0      216     4.0
42       0      218     4.0
43       0      221     4.0
44       0      222     5.0
45       0      225     5.0
46       0      230     4.0

Now let's predict the ratings that User with ID 0 will give to the movies from the test set.

In [ ]:
pred = MF_model.predict([df.userId, df.movieId])
print(pred)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step
[[4.858059 ]
 [3.917573 ]
 [4.7529655]
 [4.384852 ]
 [4.3268323]
 [5.0358024]
 [4.622041 ]
 [4.783062 ]
 [3.5620391]
 [4.1749115]
 [4.964128 ]
 [5.0641055]
 [4.306067 ]
 [4.242025 ]
 [4.525017 ]
 [5.0086436]
 [5.176332 ]
 [4.601765 ]
 [5.0006747]
 [5.018736 ]
 [4.4705443]
 [4.423999 ]
 [4.296538 ]
 [4.508616 ]
 [3.937603 ]
 [2.5243945]
 [3.6373668]
 [4.805134 ]
 [4.55998  ]
 [3.9875607]
 [4.3015456]
 [3.7981963]
 [4.114626 ]
 [3.951279 ]
 [4.4506054]
 [4.9297223]
 [4.976983 ]
 [4.9742126]
 [4.634231 ]
 [4.019106 ]
 [4.0023427]
 [4.143206 ]
 [4.3654313]
 [4.4750214]
 [4.8818283]
 [4.27744  ]
 [4.29173  ]]

In [ ]:
pd.DataFrame(pred, columns = ['rating'])

      rating
0   4.858059
1   3.917573
2   4.752965
3   4.384852
4   4.326832
5   5.035802
6   4.622041
7   4.783062
8   3.562039
9   4.174911
10  4.964128
11  5.064106
12  4.306067
13  4.242025
14  4.525017
15  5.008644
16  5.176332
17  4.601765
18  5.000675
19  5.018736
20  4.470544
21  4.423999
22  4.296538
23  4.508616
24  3.937603
25  2.524395
26  3.637367
27  4.805134
28  4.559980
29  3.987561
30  4.301546
31  3.798196
32  4.114626
33  3.951279
34  4.450605
35  4.929722
36  4.976983
37  4.974213
38  4.634231
39  4.019106
40  4.002343
41  4.143206
42  4.365431
43  4.475021
44  4.881828
45  4.277440
46  4.291730

In [ ]:
df_pred = pd.concat([df, pd.DataFrame(pred, columns = ['pred_rating'])], axis = 1)
df_pred

    userId  movieId  rating  pred_rating
0        0        0     4.0     4.858059
1        0        1     4.0     3.917573
2        0        2     4.0     4.752965
3        0        5     3.0     4.384852
4        0       14     4.0     4.326832
5        0       16     3.0     5.035802
6        0       18     5.0     4.622041
7        0       31     5.0     4.783062
8        0       39     3.0     3.562039
9        0       42     3.0     4.174911
10       0       46     5.0     4.964128
11       0       48     5.0     5.064106
12       0       55     5.0     4.306067
13       0       56     5.0     4.242025
14       0       66     4.0     4.525017
15       0       71     5.0     5.008644
16       0       72     4.0     5.176332
17       0       82     5.0     4.601765
18       0       83     3.0     5.000675
19       0       87     5.0     5.018736
20       0       88     5.0     4.470544
21       0       93     3.0     4.423999
22       0       98     5.0     4.296538
23       0      105     5.0     4.508616
24       0      107     3.0     3.937603
25       0      111     5.0     2.524395
26       0      113     4.0     3.637367
27       0      115     5.0     4.805134
28       0      117     4.0     4.559980
29       0      129     3.0     3.987561
30       0      131     4.0     4.301546
31       0      139     4.0     3.798196
32       0      149     5.0     4.114626
33       0      170     2.0     3.951279
34       0      175     4.0     4.450605
35       0      178     5.0     4.929722
36       0      184     5.0     4.976983
37       0      203     5.0     4.974213
38       0      204     4.0     4.634231
39       0      207     3.0     4.019106
40       0      215     5.0     4.002343
41       0      216     4.0     4.143206
42       0      218     4.0     4.365431
43       0      221     4.0     4.475021
44       0      222     5.0     4.881828
45       0      225     5.0     4.277440
46       0      230     4.0     4.291730

# Neural Collaborative Filtering

In this section, we instroduce a new way to do collaborative filtering with deep learning techiniques. There's a paper from 2017, titled [Neural Collaborative Filtering](https://arxiv.org/pdf/1708.05031.pdf), which describes the approach to perform collaborative filtering using neural networks.


This a fused model with two major components that contribute to the predicted rating: matrix factorization and single-layer perceptron (a dense layer), whose outputs are combined through concatenation into the last hidden dense layer:

$$
\hat{r}_{i,j} = \sigma\left(v^\top \begin{bmatrix} p_{i}^\top q_{j} \\  \sigma\left(W\begin{bmatrix}p_{i}\\q_{j}\end{bmatrix}+ b\right)\end{bmatrix}+ c\right)
$$

where $\sigma$ is a nonlinear activation fuction, e.g. ReLU.

For the impelementation, we use the Keras **functional API**. The latent user/item vectors $p_i$'s, $q_j$'s are trainable parameters from two Embedding layers. $W, v$ are the weights from dense layers, whereas $b, c$ are the bias terms repectively.

In [ ]:
from keras.layers import concatenate, Dense

In [ ]:
def NeuralMatFacto(n_movie, n_user, latent_dim):
  # Define inputs
    movie_input = Input(shape=[1])
    user_input = Input(shape=[1])

    # Embeddings
    movie_embedding = Embedding(n_movies, latent_dim)(movie_input)
    movie_vec = Flatten()(movie_embedding)

    user_embedding = Embedding(n_users, latent_dim)(user_input)
    user_vec = Flatten()(user_embedding)

    # Dense Layer
    concat = concatenate([movie_vec, user_vec])
    dense = Dense(100, activation='relu')(concat)

    # MF Layer
    mf = dot([movie_vec, user_vec], axes=1)

    # Concatenation
    combine_mlp_mf = concatenate([mf, dense])

    # Output
    rating = Dense(1, activation='relu')(combine_mlp_mf)

    model = Model([user_input, movie_input], rating)
    model.compile(loss = 'mse', optimizer = 'adam', metrics = [tf.keras.metrics.RootMeanSquaredError(name='rmse')])

    return model

In [ ]:
latent_dim = 10
NMF_model = NeuralMatFacto(n_users, n_movies, latent_dim)
NMF_model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_10      │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_11      │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_12        │ (None, 1, 10)     │     97,240 │ input_layer_10[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_13        │ (None, 1, 10)     │      6,100 │ input_layer_11[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_12          │ (None, 10)        │          0 │ embedding_12[0][… │
│ (Flatten)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_13          │ (None, 10)        │          0 │ embedding_13[0][… │
│ (Flatten)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_6       │ (None, 20)        │          0 │ flatten_12[0][0], │
│ (Concatenate)       │                   │            │ flatten_13[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_5 (Dot)         │ (None, 1)         │          0 │ flatten_12[0][0], │
│                     │                   │            │ flatten_13[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 100)       │      2,100 │ concatenate_6[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_7       │ (None, 101)       │          0 │ dot_5[0][0],      │
│ (Concatenate)       │                   │            │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 1)         │        102 │ concatenate_7[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 105,542 (412.27 KB)

 Trainable params: 105,542 (412.27 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
path_checkpt = "NMF_checkpt.weights.h5"
es_callback = EarlyStopping(monitor="val_rmse", patience=5)

modelckpt_callback = ModelCheckpoint(
    monitor="val_rmse",
    filepath=path_checkpt,
    verbose=1,
    save_weights_only=True,
    save_best_only=True,
)

In [ ]:
history = NMF_model.fit(X_tr, y_tr, validation_data=(X_te, y_te), batch_size =128, epochs=40, callbacks=[es_callback, modelckpt_callback])

Epoch 1/40
631/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.9090 - rmse: 2.1179
Epoch 1: val_rmse improved from None to 0.88656, saving model to NMF_checkpt.weights.h5

Epoch 1: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 2.1378 - rmse: 1.4621 - val_loss: 0.7860 - val_rmse: 0.8866
Epoch 2/40
628/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7091 - rmse: 0.8421
Epoch 2: val_rmse improved from 0.88656 to 0.87712, saving model to NMF_checkpt.weights.h5

Epoch 2: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7239 - rmse: 0.8508 - val_loss: 0.7693 - val_rmse: 0.8771
Epoch 3/40
621/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6733 - rmse: 0.8205
Epoch 3: val_rmse improved from 0.87712 to 0.87346, saving model to NMF_checkpt.weights.h5

Epoch 3: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6881 - rmse: 0.8295 - val_loss: 0.7629 - val_rmse: 0.8735
Epoch 4/40
617/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6518 - rmse: 0.8072
Epoch 4: val_rmse improved from 0.87346 to 0.87266, saving model to NMF_checkpt.weights.h5

Epoch 4: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.6698 - rmse: 0.8184 - val_loss: 0.7615 - val_rmse: 0.8727
Epoch 5/40
610/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6351 - rmse: 0.7969
Epoch 5: val_rmse improved from 0.87266 to 0.87005, saving model to NMF_checkpt.weights.h5

Epoch 5: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6530 - rmse: 0.8081 - val_loss: 0.7570 - val_rmse: 0.8700
Epoch 6/40
622/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6300 - rmse: 0.7937
Epoch 6: val_rmse improved from 0.87005 to 0.86740, saving model to NMF_checkpt.weights.h5

Epoch 6: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6394 - rmse: 0.7996 - val_loss: 0.7524 - val_rmse: 0.8674
Epoch 7/40
612/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6074 - rmse: 0.7793
Epoch 7: val_rmse improved from 0.86740 to 0.86468, saving model to NMF_checkpt.weights.h5

Epoch 7: finished saving model to NMF_checkpt.weights.h5
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6293 - rmse: 0.7933 - val_loss: 0.7477 - val_rmse: 0.8647
Epoch 8/40
611/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6052 - rmse: 0.7779
Epoch 8: val_rmse did not improve from 0.86468
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6197 - rmse: 0.7872 - val_loss: 0.7544 - val_rmse: 0.8685
Epoch 9/40
619/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5875 - rmse: 0.7664
Epoch 9: val_rmse did not improve from 0.86468
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6098 - rmse: 0.7809 - val_loss: 0.7546 - val_rmse: 0.8686
Epoch 10/40
617/631 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5894 - rmse: 0.7677
Epoch 10: val_rmse did not improve from 0.86468
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.5988 - rmse: 0.7738 - val_loss: 0.7481 - val_rmse: 0.8649
Epoch 11/40
623/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5789 - rmse: 0.7609
Epoch 11: val_rmse did not improve from 0.86468
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.5881 - rmse: 0.7669 - val_loss: 0.7551 - val_rmse: 0.8690
Epoch 12/40
613/631 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5585 - rmse: 0.7472
Epoch 12: val_rmse did not improve from 0.86468
631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.5757 - rmse: 0.7587 - val_loss: 0.7570 - val_rmse: 0.8700

In [ ]:
NMF_model.load_weights(path_checkpt)
NMF_model.evaluate(X_te, y_te)

631/631 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.7477 - rmse: 0.8647

[0.7476788759231567, 0.8646842837333679]

In [ ]:
pred = NMF_model.predict([df.userId, df.movieId])

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 350ms/step

In [ ]:
df_pred = pd.concat([df, pd.DataFrame(pred, columns = ['pred_rating'])], axis = 1)
df_pred

    userId  movieId  rating  pred_rating
0        0        0     4.0     4.733119
1        0        1     4.0     4.171699
2        0        2     4.0     4.558689
3        0        5     3.0     4.405311
4        0       14     4.0     4.256741
5        0       16     3.0     4.754357
6        0       18     5.0     4.559861
7        0       31     5.0     4.487778
8        0       39     3.0     3.925529
9        0       42     3.0     4.365353
10       0       46     5.0     4.725950
11       0       48     5.0     4.794688
12       0       55     5.0     4.291156
13       0       56     5.0     4.288072
14       0       66     4.0     4.420646
15       0       71     5.0     4.674067
16       0       72     4.0     4.823438
17       0       82     5.0     4.432203
18       0       83     3.0     4.722631
19       0       87     5.0     4.552008
20       0       88     5.0     4.442735
21       0       93     3.0     4.332689
22       0       98     5.0     4.197769
23       0      105     5.0     4.605302
24       0      107     3.0     4.141717
25       0      111     5.0     3.390003
26       0      113     4.0     3.976050
27       0      115     5.0     4.693416
28       0      117     4.0     4.440756
29       0      129     3.0     4.269458
30       0      131     4.0     4.354248
31       0      139     4.0     4.029261
32       0      149     5.0     4.255290
33       0      170     2.0     4.076762
34       0      175     4.0     4.536062
35       0      178     5.0     4.471445
36       0      184     5.0     4.674927
37       0      203     5.0     4.713635
38       0      204     4.0     4.296762
39       0      207     3.0     3.774369
40       0      215     5.0     4.217882
41       0      216     4.0     4.065166
42       0      218     4.0     4.481826
43       0      221     4.0     4.566088
44       0      222     5.0     4.517923
45       0      225     5.0     4.502525
46       0      230     4.0     4.400765